// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportCSV(arg1, arg2) {
  return window['go']['bridge']['App']['ExportCSV'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['bridge']['App']['GetConfig']();
}

export function GetDatabasePath() {
  return window['go']['bridge']['App']['GetDatabasePath']();
}

export function ListAntivirus() {
  return window['go']['bridge']['App']['ListAntivirus']();
}

export function ListComputers() {
  return window['go']['bridge']['App']['ListComputers']();
}

export function ListOtherSoftware() {
  return window['go']['bridge']['App']['ListOtherSoftware']();
}

export function ListSmartphones() {
  return window['go']['bridge']['App']['ListSmartphones']();
}

export function ListTablets() {
  return window['go']['bridge']['App']['ListTablets']();
}

export function ListUsers() {
  return window['go']['bridge']['App']['ListUsers']();
}

export function ListWindowsKeys() {
  return window['go']['bridge']['App']['ListWindowsKeys']();
}

export function NewDatabase(arg1) {
  return window['go']['bridge']['App']['NewDatabase'](arg1);
}

export function OpenDatabase(arg1) {
  return window['go']['bridge']['App']['OpenDatabase'](arg1);
}

export function SetConfig(arg1) {
  return window['go']['bridge']['App']['SetConfig'](arg1);
}
