// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ExportCSV(arg1:string,arg2:string):Promise<void>;

export function GetAlerts():Promise<Array<models.Alert>>;

export function GetConfig():Promise<models.AppConfig>;

export function GetDatabasePath():Promise<string>;

export function ListAntivirus():Promise<Array<models.Antivirus>>;

export function ListComputers():Promise<Array<models.Computer>>;

export function ListOtherSoftware():Promise<Array<models.OtherSoftware>>;

export function ListSmartphones():Promise<Array<models.Smartphone>>;

export function ListTablets():Promise<Array<models.Tablet>>;

export function ListUsers():Promise<Array<models.User>>;

export function ListWindowsKeys():Promise<Array<models.WindowsKey>>;

export function NewDatabase(arg1:string):Promise<void>;

export function OpenDatabase(arg1:string):Promise<void>;

export function SetConfig(arg1:models.AppConfig):Promise<void>;
