// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddAntivirus(arg1:models.AntivirusInput):Promise<void>;

export function AddComputer(arg1:models.ComputerInput):Promise<void>;

export function AddOtherSoftware(arg1:models.OtherSoftwareInput):Promise<void>;

export function AddSmartphone(arg1:models.SmartphoneInput):Promise<void>;

export function AddTablet(arg1:models.TabletInput):Promise<void>;

export function AddUser(arg1:models.UserInput):Promise<void>;

export function AddWindowsKey(arg1:models.WindowsKeyInput):Promise<void>;

export function DeleteAntivirus(arg1:number):Promise<void>;

export function DeleteComputer(arg1:number):Promise<void>;

export function DeleteOtherSoftware(arg1:number):Promise<void>;

export function DeleteSmartphone(arg1:number):Promise<void>;

export function DeleteTablet(arg1:number):Promise<void>;

export function DeleteUser(arg1:number):Promise<void>;

export function DeleteWindowsKey(arg1:number):Promise<void>;

export function ExportCSV(arg1:string):Promise<void>;

export function GetAlerts():Promise<Array<models.Alert>>;

export function GetConfig():Promise<models.AppConfig>;

export function GetDatabasePath():Promise<string>;

export function ListAntivirus():Promise<Array<models.Antivirus>>;

export function ListComputers():Promise<Array<models.Computer>>;

export function ListDevicesForDropdown():Promise<Array<models.DeviceDropdownItem>>;

export function ListOtherSoftware():Promise<Array<models.OtherSoftware>>;

export function ListSmartphones():Promise<Array<models.Smartphone>>;

export function ListTablets():Promise<Array<models.Tablet>>;

export function ListUsers():Promise<Array<models.User>>;

export function ListUsersForDropdown():Promise<Array<models.DropdownItem>>;

export function ListWindowsKeys():Promise<Array<models.WindowsKey>>;

export function NewDatabase(arg1:string):Promise<void>;

export function NewDatabaseDialog():Promise<void>;

export function OpenDatabase(arg1:string):Promise<void>;

export function OpenDatabaseDialog():Promise<void>;

export function SetConfig(arg1:models.AppConfig):Promise<void>;

export function UpdateAntivirus(arg1:number,arg2:models.AntivirusInput):Promise<void>;

export function UpdateComputer(arg1:number,arg2:models.ComputerInput):Promise<void>;

export function UpdateOtherSoftware(arg1:number,arg2:models.OtherSoftwareInput):Promise<void>;

export function UpdateSmartphone(arg1:number,arg2:models.SmartphoneInput):Promise<void>;

export function UpdateTablet(arg1:number,arg2:models.TabletInput):Promise<void>;

export function UpdateUser(arg1:number,arg2:models.UserInput):Promise<void>;

export function UpdateWindowsKey(arg1:number,arg2:models.WindowsKeyInput):Promise<void>;
