// Wails bridge runtime proxy.
// wailsjs/ bindings are generated by `wails build` (Task 9) — do NOT import from there.
// All bridge calls go through this file; components MUST NOT call window.go.* directly.

/* eslint-disable @typescript-eslint/no-explicit-any */
const app = (): any => (window as any)?.go?.bridge?.App

function call<T>(method: string, ...args: unknown[]): Promise<T> {
  const a = app()
  if (!a?.[method]) return Promise.reject(new Error(`bridge unavailable: ${method}`))
  return a[method](...args)
}

// Re-export shared types so consumers only need to import from '@/lib/api'
export type {
  Alert,
  Antivirus,
  AntivirusInput,
  AppConfig,
  Computer,
  ComputerInput,
  DeviceDropdownItem,
  DropdownItem,
  OtherSoftware,
  OtherSoftwareInput,
  Smartphone,
  SmartphoneInput,
  Tablet,
  TabletInput,
  User,
  UserInput,
  WindowsKey,
  WindowsKeyInput,
} from '@/lib/types'

import type {
  Alert,
  Antivirus,
  AntivirusInput,
  AppConfig,
  Computer,
  ComputerInput,
  DeviceDropdownItem,
  DropdownItem,
  OtherSoftware,
  OtherSoftwareInput,
  Smartphone,
  SmartphoneInput,
  Tablet,
  TabletInput,
  User,
  UserInput,
  WindowsKey,
  WindowsKeyInput,
} from '@/lib/types'

const defaultConfig: AppConfig = {
  dbPath: '',
  density: 'comfortable',
  darkMode: false,
  expiryWarningDays: 30,
}

export const listComputers = (): Promise<Computer[]> =>
  call<Computer[]>('ListComputers').catch(() => [])

export const listSmartphones = (): Promise<Smartphone[]> =>
  call<Smartphone[]>('ListSmartphones').catch(() => [])

export const listTablets = (): Promise<Tablet[]> =>
  call<Tablet[]>('ListTablets').catch(() => [])

export const listWindowsKeys = (): Promise<WindowsKey[]> =>
  call<WindowsKey[]>('ListWindowsKeys').catch(() => [])

export const listAntivirus = (): Promise<Antivirus[]> =>
  call<Antivirus[]>('ListAntivirus').catch(() => [])

export const listOtherSoftware = (): Promise<OtherSoftware[]> =>
  call<OtherSoftware[]>('ListOtherSoftware').catch(() => [])

export const listUsers = (): Promise<User[]> =>
  call<User[]>('ListUsers').catch(() => [])

export const getAlerts = (): Promise<Alert[]> =>
  call<Alert[]>('GetAlerts').catch(() => [])

export const getConfig = (): Promise<AppConfig> =>
  call<AppConfig>('GetConfig').catch(() => defaultConfig)

export const setConfig = (cfg: AppConfig): Promise<void> =>
  call<void>('SetConfig', cfg)

export const getDatabasePath = (): Promise<string> =>
  call<string>('GetDatabasePath').catch(() => '')

export const openDatabase = (path: string): Promise<void> =>
  call<void>('OpenDatabase', path)

export const newDatabase = (path: string): Promise<void> =>
  call<void>('NewDatabase', path)

export const newDatabaseDialog = (): Promise<void> =>
  call<void>('NewDatabaseDialog')

export const openDatabaseDialog = (): Promise<void> =>
  call<void>('OpenDatabaseDialog')

export const backupDatabaseDialog = (): Promise<void> =>
  call<void>('BackupDatabaseDialog')

export const exportCSV = (category: string): Promise<void> =>
  call<void>('ExportCSV', category)

// --- CRUD: Computer ---
export const addComputer = (data: ComputerInput): Promise<void> =>
  call<void>('AddComputer', data)

export const updateComputer = (id: number, data: ComputerInput): Promise<void> =>
  call<void>('UpdateComputer', id, data)

export const deleteComputer = (id: number): Promise<void> =>
  call<void>('DeleteComputer', id)

// --- CRUD: Smartphone ---
export const addSmartphone = (data: SmartphoneInput): Promise<void> =>
  call<void>('AddSmartphone', data)

export const updateSmartphone = (id: number, data: SmartphoneInput): Promise<void> =>
  call<void>('UpdateSmartphone', id, data)

export const deleteSmartphone = (id: number): Promise<void> =>
  call<void>('DeleteSmartphone', id)

// --- CRUD: Tablet ---
export const addTablet = (data: TabletInput): Promise<void> =>
  call<void>('AddTablet', data)

export const updateTablet = (id: number, data: TabletInput): Promise<void> =>
  call<void>('UpdateTablet', id, data)

export const deleteTablet = (id: number): Promise<void> =>
  call<void>('DeleteTablet', id)

// --- CRUD: WindowsKey ---
export const addWindowsKey = (data: WindowsKeyInput): Promise<void> =>
  call<void>('AddWindowsKey', data)

export const updateWindowsKey = (id: number, data: WindowsKeyInput): Promise<void> =>
  call<void>('UpdateWindowsKey', id, data)

export const deleteWindowsKey = (id: number): Promise<void> =>
  call<void>('DeleteWindowsKey', id)

// --- CRUD: Antivirus ---
export const addAntivirus = (data: AntivirusInput): Promise<void> =>
  call<void>('AddAntivirus', data)

export const updateAntivirus = (id: number, data: AntivirusInput): Promise<void> =>
  call<void>('UpdateAntivirus', id, data)

export const deleteAntivirus = (id: number): Promise<void> =>
  call<void>('DeleteAntivirus', id)

// --- CRUD: OtherSoftware ---
export const addOtherSoftware = (data: OtherSoftwareInput): Promise<void> =>
  call<void>('AddOtherSoftware', data)

export const updateOtherSoftware = (id: number, data: OtherSoftwareInput): Promise<void> =>
  call<void>('UpdateOtherSoftware', id, data)

export const deleteOtherSoftware = (id: number): Promise<void> =>
  call<void>('DeleteOtherSoftware', id)

// --- CRUD: User ---
export const addUser = (data: UserInput): Promise<void> =>
  call<void>('AddUser', data)

export const updateUser = (id: number, data: UserInput): Promise<void> =>
  call<void>('UpdateUser', id, data)

export const deleteUser = (id: number): Promise<void> =>
  call<void>('DeleteUser', id)

// --- Dropdown helpers ---
export const listUsersForDropdown = (): Promise<DropdownItem[]> =>
  call<DropdownItem[]>('ListUsersForDropdown').catch(() => [])

export const listDevicesForDropdown = (): Promise<DeviceDropdownItem[]> =>
  call<DeviceDropdownItem[]>('ListDevicesForDropdown').catch(() => [])
