// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAntivirus(arg1) {
  return window['go']['bridge']['App']['AddAntivirus'](arg1);
}

export function AddComputer(arg1) {
  return window['go']['bridge']['App']['AddComputer'](arg1);
}

export function AddOtherSoftware(arg1) {
  return window['go']['bridge']['App']['AddOtherSoftware'](arg1);
}

export function AddSmartphone(arg1) {
  return window['go']['bridge']['App']['AddSmartphone'](arg1);
}

export function AddTablet(arg1) {
  return window['go']['bridge']['App']['AddTablet'](arg1);
}

export function AddUser(arg1) {
  return window['go']['bridge']['App']['AddUser'](arg1);
}

export function AddWindowsKey(arg1) {
  return window['go']['bridge']['App']['AddWindowsKey'](arg1);
}

export function BackupDatabase(arg1) {
  return window['go']['bridge']['App']['BackupDatabase'](arg1);
}

export function BackupDatabaseDialog() {
  return window['go']['bridge']['App']['BackupDatabaseDialog']();
}

export function DeleteAntivirus(arg1) {
  return window['go']['bridge']['App']['DeleteAntivirus'](arg1);
}

export function DeleteComputer(arg1) {
  return window['go']['bridge']['App']['DeleteComputer'](arg1);
}

export function DeleteOtherSoftware(arg1) {
  return window['go']['bridge']['App']['DeleteOtherSoftware'](arg1);
}

export function DeleteSmartphone(arg1) {
  return window['go']['bridge']['App']['DeleteSmartphone'](arg1);
}

export function DeleteTablet(arg1) {
  return window['go']['bridge']['App']['DeleteTablet'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['bridge']['App']['DeleteUser'](arg1);
}

export function DeleteWindowsKey(arg1) {
  return window['go']['bridge']['App']['DeleteWindowsKey'](arg1);
}

export function ExportCSV(arg1) {
  return window['go']['bridge']['App']['ExportCSV'](arg1);
}

export function GetAlerts() {
  return window['go']['bridge']['App']['GetAlerts']();
}

export function GetConfig() {
  return window['go']['bridge']['App']['GetConfig']();
}

export function GetDatabasePath() {
  return window['go']['bridge']['App']['GetDatabasePath']();
}

export function ListAntivirus() {
  return window['go']['bridge']['App']['ListAntivirus']();
}

export function ListComputers() {
  return window['go']['bridge']['App']['ListComputers']();
}

export function ListDevicesForDropdown() {
  return window['go']['bridge']['App']['ListDevicesForDropdown']();
}

export function ListOtherSoftware() {
  return window['go']['bridge']['App']['ListOtherSoftware']();
}

export function ListSmartphones() {
  return window['go']['bridge']['App']['ListSmartphones']();
}

export function ListTablets() {
  return window['go']['bridge']['App']['ListTablets']();
}

export function ListUsers() {
  return window['go']['bridge']['App']['ListUsers']();
}

export function ListUsersForDropdown() {
  return window['go']['bridge']['App']['ListUsersForDropdown']();
}

export function ListWindowsKeys() {
  return window['go']['bridge']['App']['ListWindowsKeys']();
}

export function NewDatabase(arg1) {
  return window['go']['bridge']['App']['NewDatabase'](arg1);
}

export function NewDatabaseDialog() {
  return window['go']['bridge']['App']['NewDatabaseDialog']();
}

export function OpenDatabase(arg1) {
  return window['go']['bridge']['App']['OpenDatabase'](arg1);
}

export function OpenDatabaseDialog() {
  return window['go']['bridge']['App']['OpenDatabaseDialog']();
}

export function SetConfig(arg1) {
  return window['go']['bridge']['App']['SetConfig'](arg1);
}

export function UpdateAntivirus(arg1, arg2) {
  return window['go']['bridge']['App']['UpdateAntivirus'](arg1, arg2);
}

export function UpdateComputer(arg1, arg2) {
  return window['go']['bridge']['App']['UpdateComputer'](arg1, arg2);
}

export function UpdateOtherSoftware(arg1, arg2) {
  return window['go']['bridge']['App']['UpdateOtherSoftware'](arg1, arg2);
}

export function UpdateSmartphone(arg1, arg2) {
  return window['go']['bridge']['App']['UpdateSmartphone'](arg1, arg2);
}

export function UpdateTablet(arg1, arg2) {
  return window['go']['bridge']['App']['UpdateTablet'](arg1, arg2);
}

export function UpdateUser(arg1, arg2) {
  return window['go']['bridge']['App']['UpdateUser'](arg1, arg2);
}

export function UpdateWindowsKey(arg1, arg2) {
  return window['go']['bridge']['App']['UpdateWindowsKey'](arg1, arg2);
}
