// Wails bridge runtime proxy.
// wailsjs/ bindings are generated by `wails build` (Task 9) — do NOT import from there.
// All bridge calls go through this file; components MUST NOT call window.go.* directly.

/* eslint-disable @typescript-eslint/no-explicit-any */
const app = (): any => (window as any)?.go?.bridge?.App

function call<T>(method: string, ...args: unknown[]): Promise<T> {
  const a = app()
  if (!a?.[method]) return Promise.reject(new Error(`bridge unavailable: ${method}`))
  return a[method](...args)
}

// Re-export shared types so consumers only need to import from '@/lib/api'
export type {
  Alert,
  Antivirus,
  AppConfig,
  Computer,
  OtherSoftware,
  Smartphone,
  Tablet,
  User,
  WindowsKey,
} from '@/lib/types'

import type {
  Alert,
  Antivirus,
  AppConfig,
  Computer,
  OtherSoftware,
  Smartphone,
  Tablet,
  User,
  WindowsKey,
} from '@/lib/types'

const defaultConfig: AppConfig = {
  dbPath: '',
  density: 'comfortable',
  darkMode: false,
  expiryWarningDays: 30,
}

export const listComputers = (): Promise<Computer[]> =>
  call<Computer[]>('ListComputers').catch(() => [])

export const listSmartphones = (): Promise<Smartphone[]> =>
  call<Smartphone[]>('ListSmartphones').catch(() => [])

export const listTablets = (): Promise<Tablet[]> =>
  call<Tablet[]>('ListTablets').catch(() => [])

export const listWindowsKeys = (): Promise<WindowsKey[]> =>
  call<WindowsKey[]>('ListWindowsKeys').catch(() => [])

export const listAntivirus = (): Promise<Antivirus[]> =>
  call<Antivirus[]>('ListAntivirus').catch(() => [])

export const listOtherSoftware = (): Promise<OtherSoftware[]> =>
  call<OtherSoftware[]>('ListOtherSoftware').catch(() => [])

export const listUsers = (): Promise<User[]> =>
  call<User[]>('ListUsers').catch(() => [])

export const getAlerts = (): Promise<Alert[]> =>
  call<Alert[]>('GetAlerts').catch(() => [])

export const getConfig = (): Promise<AppConfig> =>
  call<AppConfig>('GetConfig').catch(() => defaultConfig)

export const setConfig = (cfg: AppConfig): Promise<void> =>
  call<void>('SetConfig', cfg)

export const getDatabasePath = (): Promise<string> =>
  call<string>('GetDatabasePath').catch(() => '')

export const openDatabase = (path: string): Promise<void> =>
  call<void>('OpenDatabase', path)

export const newDatabase = (path: string): Promise<void> =>
  call<void>('NewDatabase', path)

export const exportCSV = (category: string, destPath: string): Promise<void> =>
  call<void>('ExportCSV', category, destPath)
