// All Wails bridge calls go through this file.
// In scaffold phase all methods return stub values via Promise.resolve().
// DO NOT import from wailsjs/ — those bindings are generated by wails build.
// Components MUST NOT call window.go.* directly.

import type {
  Antivirus,
  AppConfig,
  Computer,
  OtherSoftware,
  Smartphone,
  Tablet,
  User,
  WindowsKey,
} from '@/lib/types'

export function listComputers(): Promise<Computer[]> {
  return Promise.resolve([])
}

export function listSmartphones(): Promise<Smartphone[]> {
  return Promise.resolve([])
}

export function listTablets(): Promise<Tablet[]> {
  return Promise.resolve([])
}

export function listWindowsKeys(): Promise<WindowsKey[]> {
  return Promise.resolve([])
}

export function listAntivirus(): Promise<Antivirus[]> {
  return Promise.resolve([])
}

export function listOtherSoftware(): Promise<OtherSoftware[]> {
  return Promise.resolve([])
}

export function listUsers(): Promise<User[]> {
  return Promise.resolve([])
}

export function getDatabasePath(): Promise<string> {
  return Promise.resolve('')
}

export function getConfig(): Promise<AppConfig> {
  return Promise.resolve({
    dbPath: '',
    density: 'comfortable',
    darkMode: false,
    expiryWarningDays: 30,
  })
}

export function setConfig(_cfg: AppConfig): Promise<void> {
  return Promise.resolve()
}

export function newDatabase(_path: string): Promise<void> {
  return Promise.resolve()
}

export function openDatabase(_path: string): Promise<void> {
  return Promise.resolve()
}

export function exportCSV(_category: string, _destPath: string): Promise<void> {
  return Promise.resolve()
}
